### PR TITLE
raise interrupted flag if InterruptedException caught in AgentRunner#close

### PR DESCRIPTION
**Pull request by zyulyaev**

### CODE REVIEW

**Comment by zyulyaev** [comment]
By the way, is interrupt flag cleared [here](https://github.com/real-logic/agrona/blob/a46c25ff06ae0cde263f6fac0d8d6129ddd8a93b/agrona/src/main/java/org/agrona/concurrent/AgentRunner.java#L236) by purpose?

**Comment by mjpt777** [comment]
It has been dealt with so cleared. I don't have a strong feeling either way as the agent thread is typically not used again.

**Comment by mjpt777** [comment]
I suppose if something in the `Agent.onClose()` wants to check the flag then best leave it set.

**Comment by zyulyaev** [comment]
Yes, for AgentRunner I agree that it is not that important. But it is for AgentInvoker, which does the same thing: [line](https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/AgentInvoker.java#L149).

**Pull request merged**
