### PR TITLE
[Java] AsciiEncoding parseIntAscii/parseLongAscii to throw NumberFormatException when detecting overflow

### PR DESCRIPTION
**Pull request by AndreyNudko**
Same behaviour as Integer::parseInt and Long::parseLong

### CODE REVIEW

**Comment by mjpt777** [comment]
I've added a more efficient approach for the common cases.

**Comment by AndreyNudko** [comment]
That's a cool way of doing this...  Thanks a lot for making that change!

**Comment by AndreyNudko** [comment]
BTW, I think there is an edge case in current code: negative integer of length 10 ("-123456789") or negative long of lenth 19 ("-123456789876543210")

Is it meant to go along the following lines?
```
        if (!isSigned)
        {
            if (length > 10 || isOverflow(MAX_INT_DIGITS, cs, i))
            {
                throw new AsciiNumberFormatException("int overflow parsing: " + cs.subSequence(index, index + length));
            }
        }
        else
        {
            if (length > 11 || isOverflow(MIN_INT_DIGITS, cs, i))
            {
                throw new AsciiNumberFormatException("int overflow parsing: " + cs.subSequence(index, index + length));
            }
        }

```

**Comment by mjpt777** [comment]
Thanks @AndreyNudko. You were correct about the missing case but the suggest approach is inefficient. I've pushed a more efficient alternative.

**Pull request closed without merging**
