### PR TITLE
BufferAlignmentException message misleading

### PR DESCRIPTION
**Pull request by sebastien-doyon**
BufferAlignmentException message always tell zero as the Buffer Alignment Offset

### CODE REVIEW

**Comment by mjpt777** [comment]
There was a build failure on this. Please run the full build to check a PR. Thanks.

**Comment by sebastien-doyon** [comment]
@mjpt777 could you please provide the build error? I have done a full build locally that was successful.
By the way, I can also contribute a modified test that validate the exception message if you like.

**Comment by sebastien-doyon** [comment]
@mjpt777 found your correction on a commit, thank you.

**Comment by mjpt777** [comment]
The failure was a checkstyle validation.  More useful tests are always great :-)

**Pull request merged**
