### PR TITLE
adding Object2IntMap which is a mirror of Int2ObjectMap

### PR DESCRIPTION
**Pull request by loveyoupeng**
copy cat of Int2ObjectHashMap and using missing value as in Int2IntHashMap

### CODE REVIEW

**Comment by mjpt777** [comment]
Thanks. Can you do a full build and make sure the code passes checkstyle? On a quick scan I cannot see how this will pass.

**Comment by loveyoupeng** [comment]
got a few warnings in checkstyle let me fix first

**Comment by loveyoupeng** [comment]
no warnings now
BTW could you submit your IDE format config to git as well :P

loveyoupeng@loveyoupeng-pc ~/Projects/opensource/fork/agrona 
$ ./gradlew 

BUILD SUCCESSFUL in 35s
29 actionable tasks: 27 executed, 2 up-to-date

**Comment by loveyoupeng** [comment]
Cool thanks

Thanks a lot
Yunpeng Li

**Comment by mjpt777** [comment]
I've cleaned up the code a little and fixed a few issues.

**Comment by loveyoupeng** [comment]
Great thx mate

Thanks a lot
Yunpeng Li

**Pull request merged**
