### PR TITLE
Assign ThreadFactory on AgentRunner construction

### PR DESCRIPTION
**Pull request by kdkavanagh**
Moves the ThreadFactory object from the static startOnThread method to the constructor of an AgentRunner.  Will be used in connection with changes to Aeron MediaDriver runners

### CODE REVIEW

**Comment by mjpt777** [comment]
Why carry around the reference to the thread factory beyond the need for thread creation during startup? Seems like temporal coupling beyond its requirements.

**Comment by kdkavanagh** [comment]
Agreed that it should not necessary to maintain the reference - Only structured it that way to avoid having to split out references to each AgentRunner in Aeron's MediaDriver and maintain the simple MediaDriver.start() method running against the List<AgentRunner>

**Comment by mjpt777** [comment]
If you want to pin media driver threads why not just search for them by name and then pin? How do you know which thread is which for the proposed approach?

**Comment by kdkavanagh** [comment]
We're looking to pin the threads of an embedded driver programmatically (w/ jni -> sched_setaffinity, etc).   https://github.com/real-logic/Aeron/pull/265 shows how we'd set ThreadFactories in the MediaDriver Context; these factories are then associated with AgentRunners using this change we're discussing here.  

Basically extending the change made in https://github.com/real-logic/Aeron/commit/98b8759ad96941699c6d3dd79c9c670488e762f1 to an embedded MediaDriver

**Pull request closed without merging**
